/// The full ISO 3166-1 country list, for fields where a person's real-world
/// address (or phone number) can be anywhere — unlike `core/countries.dart`'s
/// short pilot list of shopping-route countries, these must not be limited to
/// those. `code` is the ISO 3166-1 alpha-2 code, stored as-is by the backend.
/// `dial` is the ITU calling code (E.164 country code, no separators);
/// countries that share a numbering plan (e.g. the NANP: US/CA/Caribbean)
/// share the same `dial` — the local number carries the area code. `nameTh`
/// is the standard Thai name, shown instead of `name` when the app's locale
/// is Thai (see `worldCountryName`) — this is the country PICKER, so it must
/// follow the language toggle just like everything else in the app.
const kWorldCountries = <({String code, String name, String nameTh, String dial})>[
  (code: 'AF', name: 'Afghanistan', nameTh: 'อัฟกานิสถาน', dial: '+93'),
  (code: 'AL', name: 'Albania', nameTh: 'แอลเบเนีย', dial: '+355'),
  (code: 'DZ', name: 'Algeria', nameTh: 'แอลจีเรีย', dial: '+213'),
  (code: 'AD', name: 'Andorra', nameTh: 'อันดอร์รา', dial: '+376'),
  (code: 'AO', name: 'Angola', nameTh: 'แองโกลา', dial: '+244'),
  (code: 'AG', name: 'Antigua and Barbuda', nameTh: 'แอนติกาและบาร์บูดา', dial: '+1'),
  (code: 'AR', name: 'Argentina', nameTh: 'อาร์เจนตินา', dial: '+54'),
  (code: 'AM', name: 'Armenia', nameTh: 'อาร์เมเนีย', dial: '+374'),
  (code: 'AU', name: 'Australia', nameTh: 'ออสเตรเลีย', dial: '+61'),
  (code: 'AT', name: 'Austria', nameTh: 'ออสเตรีย', dial: '+43'),
  (code: 'AZ', name: 'Azerbaijan', nameTh: 'อาเซอร์ไบจาน', dial: '+994'),
  (code: 'BS', name: 'Bahamas', nameTh: 'บาฮามาส', dial: '+1'),
  (code: 'BH', name: 'Bahrain', nameTh: 'บาห์เรน', dial: '+973'),
  (code: 'BD', name: 'Bangladesh', nameTh: 'บังกลาเทศ', dial: '+880'),
  (code: 'BB', name: 'Barbados', nameTh: 'บาร์เบโดส', dial: '+1'),
  (code: 'BY', name: 'Belarus', nameTh: 'เบลารุส', dial: '+375'),
  (code: 'BE', name: 'Belgium', nameTh: 'เบลเยียม', dial: '+32'),
  (code: 'BZ', name: 'Belize', nameTh: 'เบลีซ', dial: '+501'),
  (code: 'BJ', name: 'Benin', nameTh: 'เบนิน', dial: '+229'),
  (code: 'BT', name: 'Bhutan', nameTh: 'ภูฏาน', dial: '+975'),
  (code: 'BO', name: 'Bolivia', nameTh: 'โบลิเวีย', dial: '+591'),
  (code: 'BA', name: 'Bosnia and Herzegovina', nameTh: 'บอสเนียและเฮอร์เซโกวีนา', dial: '+387'),
  (code: 'BW', name: 'Botswana', nameTh: 'บอตสวานา', dial: '+267'),
  (code: 'BR', name: 'Brazil', nameTh: 'บราซิล', dial: '+55'),
  (code: 'BN', name: 'Brunei', nameTh: 'บรูไน', dial: '+673'),
  (code: 'BG', name: 'Bulgaria', nameTh: 'บัลแกเรีย', dial: '+359'),
  (code: 'BF', name: 'Burkina Faso', nameTh: 'บูร์กินาฟาโซ', dial: '+226'),
  (code: 'BI', name: 'Burundi', nameTh: 'บุรุนดี', dial: '+257'),
  (code: 'KH', name: 'Cambodia', nameTh: 'กัมพูชา', dial: '+855'),
  (code: 'CM', name: 'Cameroon', nameTh: 'แคเมอรูน', dial: '+237'),
  (code: 'CA', name: 'Canada', nameTh: 'แคนาดา', dial: '+1'),
  (code: 'CV', name: 'Cape Verde', nameTh: 'เคปเวิร์ด', dial: '+238'),
  (code: 'CF', name: 'Central African Republic', nameTh: 'สาธารณรัฐแอฟริกากลาง', dial: '+236'),
  (code: 'TD', name: 'Chad', nameTh: 'ชาด', dial: '+235'),
  (code: 'CL', name: 'Chile', nameTh: 'ชิลี', dial: '+56'),
  (code: 'CN', name: 'China', nameTh: 'จีน', dial: '+86'),
  (code: 'CO', name: 'Colombia', nameTh: 'โคลอมเบีย', dial: '+57'),
  (code: 'KM', name: 'Comoros', nameTh: 'คอโมโรส', dial: '+269'),
  (code: 'CG', name: 'Congo', nameTh: 'คองโก', dial: '+242'),
  (code: 'CD', name: 'Congo (DRC)', nameTh: 'คองโก (สาธารณรัฐประชาธิปไตย)', dial: '+243'),
  (code: 'CR', name: 'Costa Rica', nameTh: 'คอสตาริกา', dial: '+506'),
  (code: 'CI', name: "Côte d'Ivoire", nameTh: 'ไอวอรีโคสต์', dial: '+225'),
  (code: 'HR', name: 'Croatia', nameTh: 'โครเอเชีย', dial: '+385'),
  (code: 'CU', name: 'Cuba', nameTh: 'คิวบา', dial: '+53'),
  (code: 'CY', name: 'Cyprus', nameTh: 'ไซปรัส', dial: '+357'),
  (code: 'CZ', name: 'Czechia', nameTh: 'เช็กเกีย', dial: '+420'),
  (code: 'DK', name: 'Denmark', nameTh: 'เดนมาร์ก', dial: '+45'),
  (code: 'DJ', name: 'Djibouti', nameTh: 'จิบูตี', dial: '+253'),
  (code: 'DM', name: 'Dominica', nameTh: 'โดมินิกา', dial: '+1'),
  (code: 'DO', name: 'Dominican Republic', nameTh: 'สาธารณรัฐโดมินิกัน', dial: '+1'),
  (code: 'EC', name: 'Ecuador', nameTh: 'เอกวาดอร์', dial: '+593'),
  (code: 'EG', name: 'Egypt', nameTh: 'อียิปต์', dial: '+20'),
  (code: 'SV', name: 'El Salvador', nameTh: 'เอลซัลวาดอร์', dial: '+503'),
  (code: 'GQ', name: 'Equatorial Guinea', nameTh: 'อิเควทอเรียลกินี', dial: '+240'),
  (code: 'ER', name: 'Eritrea', nameTh: 'เอริเทรีย', dial: '+291'),
  (code: 'EE', name: 'Estonia', nameTh: 'เอสโตเนีย', dial: '+372'),
  (code: 'SZ', name: 'Eswatini', nameTh: 'เอสวาตินี', dial: '+268'),
  (code: 'ET', name: 'Ethiopia', nameTh: 'เอธิโอเปีย', dial: '+251'),
  (code: 'FJ', name: 'Fiji', nameTh: 'ฟิจิ', dial: '+679'),
  (code: 'FI', name: 'Finland', nameTh: 'ฟินแลนด์', dial: '+358'),
  (code: 'FR', name: 'France', nameTh: 'ฝรั่งเศส', dial: '+33'),
  (code: 'GA', name: 'Gabon', nameTh: 'กาบอง', dial: '+241'),
  (code: 'GM', name: 'Gambia', nameTh: 'แกมเบีย', dial: '+220'),
  (code: 'GE', name: 'Georgia', nameTh: 'จอร์เจีย', dial: '+995'),
  (code: 'DE', name: 'Germany', nameTh: 'เยอรมนี', dial: '+49'),
  (code: 'GH', name: 'Ghana', nameTh: 'กานา', dial: '+233'),
  (code: 'GR', name: 'Greece', nameTh: 'กรีซ', dial: '+30'),
  (code: 'GD', name: 'Grenada', nameTh: 'เกรเนดา', dial: '+1'),
  (code: 'GT', name: 'Guatemala', nameTh: 'กัวเตมาลา', dial: '+502'),
  (code: 'GN', name: 'Guinea', nameTh: 'กินี', dial: '+224'),
  (code: 'GW', name: 'Guinea-Bissau', nameTh: 'กินี-บิสเซา', dial: '+245'),
  (code: 'GY', name: 'Guyana', nameTh: 'กายอานา', dial: '+592'),
  (code: 'HT', name: 'Haiti', nameTh: 'เฮติ', dial: '+509'),
  (code: 'HN', name: 'Honduras', nameTh: 'ฮอนดูรัส', dial: '+504'),
  (code: 'HK', name: 'Hong Kong', nameTh: 'ฮ่องกง', dial: '+852'),
  (code: 'HU', name: 'Hungary', nameTh: 'ฮังการี', dial: '+36'),
  (code: 'IS', name: 'Iceland', nameTh: 'ไอซ์แลนด์', dial: '+354'),
  (code: 'IN', name: 'India', nameTh: 'อินเดีย', dial: '+91'),
  (code: 'ID', name: 'Indonesia', nameTh: 'อินโดนีเซีย', dial: '+62'),
  (code: 'IR', name: 'Iran', nameTh: 'อิหร่าน', dial: '+98'),
  (code: 'IQ', name: 'Iraq', nameTh: 'อิรัก', dial: '+964'),
  (code: 'IE', name: 'Ireland', nameTh: 'ไอร์แลนด์', dial: '+353'),
  (code: 'IL', name: 'Israel', nameTh: 'อิสราเอล', dial: '+972'),
  (code: 'IT', name: 'Italy', nameTh: 'อิตาลี', dial: '+39'),
  (code: 'JM', name: 'Jamaica', nameTh: 'จาเมกา', dial: '+1'),
  (code: 'JP', name: 'Japan', nameTh: 'ญี่ปุ่น', dial: '+81'),
  (code: 'JO', name: 'Jordan', nameTh: 'จอร์แดน', dial: '+962'),
  (code: 'KZ', name: 'Kazakhstan', nameTh: 'คาซัคสถาน', dial: '+7'),
  (code: 'KE', name: 'Kenya', nameTh: 'เคนยา', dial: '+254'),
  (code: 'KI', name: 'Kiribati', nameTh: 'คิริบาส', dial: '+686'),
  (code: 'KW', name: 'Kuwait', nameTh: 'คูเวต', dial: '+965'),
  (code: 'KG', name: 'Kyrgyzstan', nameTh: 'คีร์กีซสถาน', dial: '+996'),
  (code: 'LA', name: 'Laos', nameTh: 'ลาว', dial: '+856'),
  (code: 'LV', name: 'Latvia', nameTh: 'ลัตเวีย', dial: '+371'),
  (code: 'LB', name: 'Lebanon', nameTh: 'เลบานอน', dial: '+961'),
  (code: 'LS', name: 'Lesotho', nameTh: 'เลโซโท', dial: '+266'),
  (code: 'LR', name: 'Liberia', nameTh: 'ไลบีเรีย', dial: '+231'),
  (code: 'LY', name: 'Libya', nameTh: 'ลิเบีย', dial: '+218'),
  (code: 'LI', name: 'Liechtenstein', nameTh: 'ลิกเตนสไตน์', dial: '+423'),
  (code: 'LT', name: 'Lithuania', nameTh: 'ลิทัวเนีย', dial: '+370'),
  (code: 'LU', name: 'Luxembourg', nameTh: 'ลักเซมเบิร์ก', dial: '+352'),
  (code: 'MO', name: 'Macau', nameTh: 'มาเก๊า', dial: '+853'),
  (code: 'MG', name: 'Madagascar', nameTh: 'มาดากัสการ์', dial: '+261'),
  (code: 'MW', name: 'Malawi', nameTh: 'มาลาวี', dial: '+265'),
  (code: 'MY', name: 'Malaysia', nameTh: 'มาเลเซีย', dial: '+60'),
  (code: 'MV', name: 'Maldives', nameTh: 'มัลดีฟส์', dial: '+960'),
  (code: 'ML', name: 'Mali', nameTh: 'มาลี', dial: '+223'),
  (code: 'MT', name: 'Malta', nameTh: 'มอลตา', dial: '+356'),
  (code: 'MH', name: 'Marshall Islands', nameTh: 'หมู่เกาะมาร์แชลล์', dial: '+692'),
  (code: 'MR', name: 'Mauritania', nameTh: 'มอริเตเนีย', dial: '+222'),
  (code: 'MU', name: 'Mauritius', nameTh: 'มอริเชียส', dial: '+230'),
  (code: 'MX', name: 'Mexico', nameTh: 'เม็กซิโก', dial: '+52'),
  (code: 'FM', name: 'Micronesia', nameTh: 'ไมโครนีเซีย', dial: '+691'),
  (code: 'MD', name: 'Moldova', nameTh: 'มอลโดวา', dial: '+373'),
  (code: 'MC', name: 'Monaco', nameTh: 'โมนาโก', dial: '+377'),
  (code: 'MN', name: 'Mongolia', nameTh: 'มองโกเลีย', dial: '+976'),
  (code: 'ME', name: 'Montenegro', nameTh: 'มอนเตเนโกร', dial: '+382'),
  (code: 'MA', name: 'Morocco', nameTh: 'โมร็อกโก', dial: '+212'),
  (code: 'MZ', name: 'Mozambique', nameTh: 'โมซัมบิก', dial: '+258'),
  (code: 'MM', name: 'Myanmar', nameTh: 'เมียนมา', dial: '+95'),
  (code: 'NA', name: 'Namibia', nameTh: 'นามิเบีย', dial: '+264'),
  (code: 'NR', name: 'Nauru', nameTh: 'นาอูรู', dial: '+674'),
  (code: 'NP', name: 'Nepal', nameTh: 'เนปาล', dial: '+977'),
  (code: 'NL', name: 'Netherlands', nameTh: 'เนเธอร์แลนด์', dial: '+31'),
  (code: 'NZ', name: 'New Zealand', nameTh: 'นิวซีแลนด์', dial: '+64'),
  (code: 'NI', name: 'Nicaragua', nameTh: 'นิการากัว', dial: '+505'),
  (code: 'NE', name: 'Niger', nameTh: 'ไนเจอร์', dial: '+227'),
  (code: 'NG', name: 'Nigeria', nameTh: 'ไนจีเรีย', dial: '+234'),
  (code: 'KP', name: 'North Korea', nameTh: 'เกาหลีเหนือ', dial: '+850'),
  (code: 'MK', name: 'North Macedonia', nameTh: 'นอร์ทมาซิโดเนีย', dial: '+389'),
  (code: 'NO', name: 'Norway', nameTh: 'นอร์เวย์', dial: '+47'),
  (code: 'OM', name: 'Oman', nameTh: 'โอมาน', dial: '+968'),
  (code: 'PK', name: 'Pakistan', nameTh: 'ปากีสถาน', dial: '+92'),
  (code: 'PW', name: 'Palau', nameTh: 'ปาเลา', dial: '+680'),
  (code: 'PS', name: 'Palestine', nameTh: 'ปาเลสไตน์', dial: '+970'),
  (code: 'PA', name: 'Panama', nameTh: 'ปานามา', dial: '+507'),
  (code: 'PG', name: 'Papua New Guinea', nameTh: 'ปาปัวนิวกินี', dial: '+675'),
  (code: 'PY', name: 'Paraguay', nameTh: 'ปารากวัย', dial: '+595'),
  (code: 'PE', name: 'Peru', nameTh: 'เปรู', dial: '+51'),
  (code: 'PH', name: 'Philippines', nameTh: 'ฟิลิปปินส์', dial: '+63'),
  (code: 'PL', name: 'Poland', nameTh: 'โปแลนด์', dial: '+48'),
  (code: 'PT', name: 'Portugal', nameTh: 'โปรตุเกส', dial: '+351'),
  (code: 'QA', name: 'Qatar', nameTh: 'กาตาร์', dial: '+974'),
  (code: 'RO', name: 'Romania', nameTh: 'โรมาเนีย', dial: '+40'),
  (code: 'RU', name: 'Russia', nameTh: 'รัสเซีย', dial: '+7'),
  (code: 'RW', name: 'Rwanda', nameTh: 'รวันดา', dial: '+250'),
  (code: 'KN', name: 'Saint Kitts and Nevis', nameTh: 'เซนต์คิตส์และเนวิส', dial: '+1'),
  (code: 'LC', name: 'Saint Lucia', nameTh: 'เซนต์ลูเซีย', dial: '+1'),
  (code: 'VC', name: 'Saint Vincent and the Grenadines', nameTh: 'เซนต์วินเซนต์และเกรนาดีนส์', dial: '+1'),
  (code: 'WS', name: 'Samoa', nameTh: 'ซามัว', dial: '+685'),
  (code: 'SM', name: 'San Marino', nameTh: 'ซานมารีโน', dial: '+378'),
  (code: 'ST', name: 'Sao Tome and Principe', nameTh: 'เซาตูเมและปรินซิปี', dial: '+239'),
  (code: 'SA', name: 'Saudi Arabia', nameTh: 'ซาอุดีอาระเบีย', dial: '+966'),
  (code: 'SN', name: 'Senegal', nameTh: 'เซเนกัล', dial: '+221'),
  (code: 'RS', name: 'Serbia', nameTh: 'เซอร์เบีย', dial: '+381'),
  (code: 'SC', name: 'Seychelles', nameTh: 'เซเชลส์', dial: '+248'),
  (code: 'SL', name: 'Sierra Leone', nameTh: 'เซียร์ราลีโอน', dial: '+232'),
  (code: 'SG', name: 'Singapore', nameTh: 'สิงคโปร์', dial: '+65'),
  (code: 'SK', name: 'Slovakia', nameTh: 'สโลวาเกีย', dial: '+421'),
  (code: 'SI', name: 'Slovenia', nameTh: 'สโลวีเนีย', dial: '+386'),
  (code: 'SB', name: 'Solomon Islands', nameTh: 'หมู่เกาะโซโลมอน', dial: '+677'),
  (code: 'SO', name: 'Somalia', nameTh: 'โซมาเลีย', dial: '+252'),
  (code: 'ZA', name: 'South Africa', nameTh: 'แอฟริกาใต้', dial: '+27'),
  (code: 'KR', name: 'South Korea', nameTh: 'เกาหลีใต้', dial: '+82'),
  (code: 'SS', name: 'South Sudan', nameTh: 'ซูดานใต้', dial: '+211'),
  (code: 'ES', name: 'Spain', nameTh: 'สเปน', dial: '+34'),
  (code: 'LK', name: 'Sri Lanka', nameTh: 'ศรีลังกา', dial: '+94'),
  (code: 'SD', name: 'Sudan', nameTh: 'ซูดาน', dial: '+249'),
  (code: 'SR', name: 'Suriname', nameTh: 'ซูรินาเม', dial: '+597'),
  (code: 'SE', name: 'Sweden', nameTh: 'สวีเดน', dial: '+46'),
  (code: 'CH', name: 'Switzerland', nameTh: 'สวิตเซอร์แลนด์', dial: '+41'),
  (code: 'SY', name: 'Syria', nameTh: 'ซีเรีย', dial: '+963'),
  (code: 'TW', name: 'Taiwan', nameTh: 'ไต้หวัน', dial: '+886'),
  (code: 'TJ', name: 'Tajikistan', nameTh: 'ทาจิกิสถาน', dial: '+992'),
  (code: 'TZ', name: 'Tanzania', nameTh: 'แทนซาเนีย', dial: '+255'),
  (code: 'TH', name: 'Thailand', nameTh: 'ไทย', dial: '+66'),
  (code: 'TL', name: 'Timor-Leste', nameTh: 'ติมอร์-เลสเต', dial: '+670'),
  (code: 'TG', name: 'Togo', nameTh: 'โตโก', dial: '+228'),
  (code: 'TO', name: 'Tonga', nameTh: 'ตองงา', dial: '+676'),
  (code: 'TT', name: 'Trinidad and Tobago', nameTh: 'ตรินิแดดและโตเบโก', dial: '+1'),
  (code: 'TN', name: 'Tunisia', nameTh: 'ตูนิเซีย', dial: '+216'),
  (code: 'TR', name: 'Turkey', nameTh: 'ตุรกี', dial: '+90'),
  (code: 'TM', name: 'Turkmenistan', nameTh: 'เติร์กเมนิสถาน', dial: '+993'),
  (code: 'TV', name: 'Tuvalu', nameTh: 'ตูวาลู', dial: '+688'),
  (code: 'UG', name: 'Uganda', nameTh: 'ยูกันดา', dial: '+256'),
  (code: 'UA', name: 'Ukraine', nameTh: 'ยูเครน', dial: '+380'),
  (code: 'AE', name: 'United Arab Emirates', nameTh: 'สหรัฐอาหรับเอมิเรตส์', dial: '+971'),
  (code: 'GB', name: 'United Kingdom', nameTh: 'สหราชอาณาจักร', dial: '+44'),
  (code: 'US', name: 'United States', nameTh: 'สหรัฐอเมริกา', dial: '+1'),
  (code: 'UY', name: 'Uruguay', nameTh: 'อุรุกวัย', dial: '+598'),
  (code: 'UZ', name: 'Uzbekistan', nameTh: 'อุซเบกิสถาน', dial: '+998'),
  (code: 'VU', name: 'Vanuatu', nameTh: 'วานูอาตู', dial: '+678'),
  (code: 'VA', name: 'Vatican City', nameTh: 'นครวาติกัน', dial: '+379'),
  (code: 'VE', name: 'Venezuela', nameTh: 'เวเนซุเอลา', dial: '+58'),
  (code: 'VN', name: 'Vietnam', nameTh: 'เวียดนาม', dial: '+84'),
  (code: 'YE', name: 'Yemen', nameTh: 'เยเมน', dial: '+967'),
  (code: 'ZM', name: 'Zambia', nameTh: 'แซมเบีย', dial: '+260'),
  (code: 'ZW', name: 'Zimbabwe', nameTh: 'ซิมบับเว', dial: '+263'),
];

/// [locale] is an [AppLocalizations.localeName] ('en' | 'th') — pass
/// `AppLocalizations.of(context)!.localeName` from a widget's `build`.
String worldCountryName(String? code, [String locale = 'en']) {
  if (code == null || code.isEmpty) return '';
  for (final c in kWorldCountries) {
    if (c.code == code) return locale == 'th' ? c.nameTh : c.name;
  }
  return code;
}

String? dialCodeFor(String? code) {
  if (code == null || code.isEmpty) return null;
  for (final c in kWorldCountries) {
    if (c.code == code) return c.dial;
  }
  return null;
}

/// Countries whose top-level administrative division is officially (or very
/// commonly, in translation) called a "Province" rather than a "City" —
/// used only to pick a friendlier label on a free-text address field, not to
/// validate or look up real subdivisions. Not exhaustive (many more
/// countries use "state", "region", "county", etc. — those keep the generic
/// "City" label). Thailand is deliberately excluded: it gets its own real
/// province/district/sub-district dataset and cascading picker instead (see
/// `ThaiAddressPicker`).
const _provinceLabelCountries = <String>{
  'AF', 'AR', 'BE', 'BF', 'CA', 'CN', 'CR', 'CU', 'CD', 'EC', 'GA', 'ID',
  'IR', 'IT', 'KH', 'KP', 'KR', 'LA', 'LK', 'MZ', 'MN', 'NL', 'PK', 'PA',
  'PG', 'PH', 'RW', 'SA', 'SB', 'ES', 'TR', 'VN', 'ZA', 'ZM', 'ZW',
};

bool usesProvinceLabel(String? code) =>
    code != null && _provinceLabelCountries.contains(code.toUpperCase());
