// PLACEHOLDER — replace this whole file before push notifications will work.
//
// This is normally generated by running `flutterfire configure` from the
// `mobile/` directory once you have a Firebase project. That command reads
// your project and overwrites this file with real values for every platform
// you select. Until then, every value below is a non-functional placeholder
// (`Firebase.initializeApp()` is wrapped in a try/catch in `main.dart`
// specifically so a placeholder config degrades to "push disabled" instead
// of crashing the app).
//
// Steps:
//   1. Create a Firebase project at https://console.firebase.google.com.
//   2. Add an Android app with package name `com.hiww.hiww_mobile`
//      (see `android/app/build.gradle.kts`'s `applicationId`) and download
//      the generated `google-services.json` into `android/app/`.
//   3. Add a Web app in the same project; Firebase shows you its config
//      object on-screen (apiKey, appId, messagingSenderId, projectId...).
//   4. Run `dart pub global activate flutterfire_cli`, then from `mobile/`:
//      `flutterfire configure` — pick the same project, select Android and
//      Web when prompted. This regenerates this file for you with the real
//      values; you can safely delete everything below once that's done.
//   5. For Web push specifically, also set the same Web `apiKey` etc. in
//      `web/firebase-messaging-sw.js` (see that file's own placeholders).
//
// See also: `docs/PUSH_NOTIFICATIONS.md` for the full setup guide, including
// the backend service-account side.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform yet — '
          'this pilot only wires up Android and Web. Run `flutterfire configure` '
          'to add another platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB38t8wRYjnigtEAgHZMbnesAi2-p-KyLw',
    appId: '1:696163754096:android:7068d270436c82aad114b5',
    messagingSenderId: '696163754096',
    projectId: 'hiww-d1f5c',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCej8Pm_1hEcleuNSiD3a-zvQJOXrX8h4s',
    appId: '1:696163754096:web:17e96c2165a97395d114b5',
    messagingSenderId: '696163754096',
    projectId: 'hiww-d1f5c',
    authDomain: 'hiww-d1f5c.firebaseapp.com',
    storageBucket: 'hiww-d1f5c.firebasestorage.app',
    // Web push additionally needs a VAPID key, generated in the Firebase
    // console under Project settings -> Cloud Messaging -> Web configuration
    // -> "Web Push certificates". Set it in
    // `lib/features/push/push_service.dart`'s `_webVapidKey` once you have one.
  );
}
